((nil         . ((indent-tabs-mode             . nil)
                 (fill-column                  . 80)))
 (erlang-mode . ((flycheck-erlang-include-path . ("../_build/test/lib"))
                 (flycheck-erlang-library-path . ("../_build/test/lib/*/ebin"))
                 (erlang-indent-level          . 2))))
